# Generated by Django 5.1 on 2026-01-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20260124_1416'),
    ]

    operations = [
    ]
